---

- import_tasks: locales.yml

- name: check if sshd is installed
  command: dpkg -L openssh-server
  register: openssh_server_dpkg

- import_tasks: ssh.yml
  when:
    - locale_stop | default(true) | bool
    - openssh_server_dpkg | succeeded
