---

- include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: install libselinux-python dep for rhel/centos
  yum:
    name: libselinux-python
    state: present
  become: yes
  when: ansible_pkg_mgr == "yum"

- name: stop accepting locale env vars from your client to the server
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^AcceptEnv LANG LC_(.+)"
    line: "#AcceptEnv LANG LC_\\1"
    backrefs: yes
  when: locale_stop
  become: yes
  notify: restart_{{ ssh_service_name }}
